ADHD-Manager/Controllers/PomodoroTimerController.cs
using ADHD_Manager.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Timers;

namespace ADHD_Manager.Controllers
{
    public class PomodoroTimerController : Controller
    {
        private PomodoroTimer _timer;
        private System.Timers.Timer _countDownTimer;
        private int _remainingSeconds;
        private bool _shortBreak { get; set; }
        private bool _longBreak { get; set; }

        public PomodoroTimerController()
        {
            _timer = new PomodoroTimer();
        }

        public IActionResult Index()
        {
            return View(_timer);
        }

        public IActionResult Start()
        {
            _timer.IsRunning = true;

            if (_remainingSeconds <= 0)
            {
                SetTime(_shortBreak, _longBreak);
            }

            // Create and start the countdown timer
            _countDownTimer = new System.Timers.Timer(1000);
            _countDownTimer.Elapsed += CountDownTimerCallBack;
            _countDownTimer.AutoReset = true;
            _countDownTimer.Enabled = true;

            return Ok(_remainingSeconds);
        }

        private async void CountDownTimerCallBack(object sender, ElapsedEventArgs e)
        {
            _remainingSeconds--;

            if (_remainingSeconds <= 0)
            {
                // Stop timer if the countdown reaches zero
                _countDownTimer.Dispose();
                _timer.IsRunning = false;
                _countDownTimer.Enabled = false;

                // Create something else to trigger here to prompt user to take a short break
            }
        }

        public IActionResult Stop(System.Timers.Timer _countDownTimer)
        {
            _countDownTimer.Enabled = false;
            _countDownTimer.Dispose();
            _timer.IsRunning = false;

            // Stop Timer logic here

            return Ok();
        }

        public IActionResult Reset()
        {
            // _timer.StartTime = 25 * 60;
            _timer.StartTime = SetTime(_shortBreak, _longBreak);
            _timer.IsRunning = false;

            return Ok(_timer.StartTime);
        }

        public IActionResult SetPomodoroTime()
        {
            _shortBreak = false;
            _longBreak = false;
            SetTime(_shortBreak, _longBreak);

            return Ok(_remainingSeconds);
        }

        public IActionResult SetShortBreak()
        {
            _shortBreak = true;
            _longBreak = false;
            SetTime(_shortBreak, _longBreak);

            return Ok(_remainingSeconds);
        }
        public IActionResult SetLongBreak()
        {
            _shortBreak = false;
            _longBreak = true;
            SetTime(_shortBreak, _longBreak);

            return Ok(_remainingSeconds);
        }

        private int SetTime(bool _shortBreak, bool _longBreak)
        {
            if (_shortBreak == false && _longBreak == true)
            {
                _remainingSeconds = 15 * 60;
            }
            else if (_shortBreak == true && _longBreak == false)
            {
                _remainingSeconds = 5 * 60;
            }
            else
            {
                _remainingSeconds = 25 * 60;
            }

            return _remainingSeconds;
        }
    }
}

ADHD-Manager/Controllers/TasksController.cs
using ADHD_Manager.Models;
using ADHD_Manager.Models.Data;
using Microsoft.AspNetCore.Mvc;

namespace ADHD_Manager.Controllers
{
    public class TasksController : Controller
    {
        private readonly ITasksRepository repo;

        public TasksController(ITasksRepository repo)
        {
            this.repo = repo;
        }

        public IActionResult Index(string categoryFilter, string statusFilter)
        {
            var tasks = repo.GetAllTasks();

            if (!string.IsNullOrEmpty(categoryFilter))
            {
                int categoryId = int.Parse(categoryFilter);
                tasks = tasks.Where(t => t.CategoryId == categoryId);
            }

            if (!string.IsNullOrEmpty(statusFilter))
            {
                int statusId = int.Parse(statusFilter);
                tasks = tasks.Where(t => t.StatusId == statusId);
            }

            DateTime currentTime = DateTime.Now;
            foreach (var task in tasks)
            {
                if (currentTime > task.DueDate && task.StatusId != 2)
                {
                    task.StatusId = 3;
                    repo.UpdateStatusTasks(task);
                }
            }

            return View(tasks);
        }

        public IActionResult ViewTasks(int id)
        {
            var task = repo.GetTask(id);
            return View(task);
        }

        public IActionResult UpdateTasks(int id)
        {
            Tasks task = repo.GetTask(id);

            var statusList = repo.GetStatus();
            var categoriesList = repo.GetCategories();

            task.Categories = categoriesList;
            task.Statuses = statusList;


            if (task == null)
            {
                return View("Error: TaskNotFound");
            }
            return View(task);
        }

        public IActionResult UpdateTaskToDatabase(Tasks task)
        {
            repo.UpdateTasks(task);
            return RedirectToAction("ViewTasks", new { id = task.TaskID });
        }

        public IActionResult InsertTasks()
        {
            var newTask = repo.AssignCategoryAndStatus();
            return View(newTask);
        }

        public IActionResult InsertTaskToDatabase(Tasks taskToInsert)
        {
            repo.InsertTasks(taskToInsert);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteTasks(Tasks task)
        {
            repo.DeleteTasks(task);
            return RedirectToAction("Index");
        }

        public IActionResult CompleteTasks(int id)
        {
            repo.CompleteTasks(id);
            return RedirectToAction("Index");
        }
    }
}

ADHD-Manager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ADDFocus</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ADHD_Manager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ADDFocus</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Tasks" asp-action="Index">Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="PomodoroTimer" asp-action="Index">Pomodoro</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <p class="m-3">@DateTime.Now.ToString("MM-dd-yyyy h:mm tt")</p>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ADDFocus - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <p id="notice" class="text center p-2 w-30">NOTICE:<br>This application is currently under development.</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>